spring.application.name=Discografia
spring.data.mongodb.uri=mongodb+srv://eva2_spring:dcYcU9z49px2whYXRD@cluster-spring.kptf7tm.mongodb.net/?appName=cluster-spring
spring.data.mongodb.database=discografica-db

       